# Generated by Django 5.2.5 on 2025-10-07 23:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('boundary_coords', models.JSONField(blank=True, null=True)),
                ('rera_number', models.CharField(blank=True, max_length=200, null=True)),
                ('project_type', models.CharField(default='Residential', max_length=50)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('possession_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Pre-Launch', max_length=50)),
                ('total_area', models.FloatField(blank=True, null=True)),
                ('total_units', models.IntegerField(default=0)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amenities', models.JSONField(blank=True, null=True)),
                ('tax_details', models.JSONField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('area_sqft', models.FloatField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('block_type', models.CharField(default='Tower', max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('footprint_coords', models.JSONField(blank=True, null=True)),
                ('total_floors', models.IntegerField(blank=True, null=True)),
                ('total_units', models.IntegerField(blank=True, null=True)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='inventory.project')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_number', models.CharField(max_length=100)),
                ('unit_type', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('polygon_coords', models.JSONField(blank=True, null=True)),
                ('floor_number', models.IntegerField(blank=True, null=True)),
                ('carpet_area', models.FloatField(blank=True, null=True)),
                ('super_built_area', models.FloatField(blank=True, null=True)),
                ('plot_size', models.FloatField(blank=True, null=True)),
                ('facing', models.CharField(blank=True, max_length=50, null=True)),
                ('view_type', models.CharField(blank=True, max_length=50, null=True)),
                ('vastu_compliant', models.BooleanField(default=False)),
                ('parking_count', models.IntegerField(default=0)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('plc_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('floor_rise_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amenities', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Blocked', 'Blocked'), ('Booked', 'Booked'), ('Sold', 'Sold'), ('Cancelled', 'Cancelled'), ('Under Agreement', 'Under Agreement'), ('Handed Over', 'Handed Over')], default='Available', max_length=50)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('blocked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='inventory.block')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='inventory.project')),
            ],
        ),
    ]
