# Generated by Django 5.2.5 on 2025-10-08 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
    ]
